org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=1G -XX:+HeapDumpOnOutOfMemoryError
org.gradle.java.home=C:/Tools/jdk-17.0.12+7
android.useAndroidX=true
android.builtInKotlin=false
android.newDsl=false
systemProp.ANDROID_USER_HOME=C:/Users/SANVEE~1/.android
kotlin.compiler.execution.strategy=in-process
kotlin.incremental=false
